SRC_DIR = ../src
TEST_SRC_DIR=.

SOURCES_C := \
    $(SRC_DIR)/miniz/miniz.c \

SOURCES_CXX := \
    $(TEST_SRC_DIR)/main.cpp \
    $(SRC_DIR)/geargrafx_core.cpp \
    $(SRC_DIR)/audio.cpp \
    $(SRC_DIR)/cartridge.cpp \
    $(SRC_DIR)/huc6202.cpp \
    $(SRC_DIR)/huc6260.cpp \
    $(SRC_DIR)/huc6270.cpp \
    $(SRC_DIR)/huc6280.cpp \
    $(SRC_DIR)/huc6280_functors.cpp \
    $(SRC_DIR)/huc6280_opcodes.cpp \
    $(SRC_DIR)/huc6280_psg.cpp \
    $(SRC_DIR)/input.cpp \
    $(SRC_DIR)/mapper.cpp \
    $(SRC_DIR)/memory.cpp \
    $(SRC_DIR)/sf2_mapper.cpp \
