/*
 * Geargrafx - PC Engine / TurboGrafx Emulator
 * Copyright (C) 2024  Ignacio Sanchez

 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * any later version.

 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.

 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see http://www.gnu.org/licenses/
 *
 */
#ifndef HUC6280_NAME_H
#define HUC6280_NAME_H

enum GG_OPCode_Type
{
    GG_OPCode_Type_Implied,
    GG_OPCode_Type_1b,
    GG_OPCode_Type_1b_1b,
    GG_OPCode_Type_1b_2b,
    GG_OPCode_Type_2b,
    GG_OPCode_Type_2b_2b_2b,
    GG_OPCode_Type_1b_Relative,
    GG_OPCode_Type_1b_1b_Relative,
    GG_OPCode_Type_ST0,
    GG_OPCode_Type_BRK,
    GG_OPCode_Type_MPR,
};

struct GG_OPCode_Info
{
    const char* name[GG_Disassembler_Syntax_Count];
    GG_OPCode_Type type;
};

#define GG_OPCODE(name, type) { { name, name, name }, type }
#define GG_OPCODE_SYNTAX(geargrafx, pceas, wladx, type) { { geargrafx, pceas, wladx }, type }

static const GG_OPCode_Info k_huc6280_opcode_names[256] = {
    GG_OPCODE_SYNTAX("{n}BRK", "{n}BRK", "{n}BRK {o}$%02X", GG_OPCode_Type_BRK),
    GG_OPCODE_SYNTAX("{n}ORA {o}$(%02X,X)", "{n}ORA {o}[$%02X,X]", "{n}ORA {o}($%02X,X)", GG_OPCode_Type_1b),
    GG_OPCODE("{n}SXY", GG_OPCode_Type_Implied),
    GG_OPCODE_SYNTAX("{n}ST0 {o}#$%02X  {e}[REG = %s]", "{n}ST0 {o}#$%02X", "{n}ST0 {o}#$%02X", GG_OPCode_Type_ST0),
    GG_OPCODE_SYNTAX("{n}TSB {o}$%02X", "{n}TSB {o}<$%02X", "{n}TSB {o}$%02X", GG_OPCode_Type_1b),
    GG_OPCODE_SYNTAX("{n}ORA {o}$%02X", "{n}ORA {o}<$%02X", "{n}ORA {o}$%02X", GG_OPCode_Type_1b),
    GG_OPCODE_SYNTAX("{n}ASL {o}$%02X", "{n}ASL {o}<$%02X", "{n}ASL {o}$%02X", GG_OPCode_Type_1b),
    GG_OPCODE_SYNTAX("{n}RMB {o}0,$%02X", "{n}RMB0 {o}<$%02X", "{n}RMB0 {o}$%02X", GG_OPCode_Type_1b),
    GG_OPCODE("{n}PHP", GG_OPCode_Type_Implied),
    GG_OPCODE("{n}ORA {o}#$%02X", GG_OPCode_Type_1b),
    GG_OPCODE("{n}ASL {o}A", GG_OPCode_Type_Implied),
    GG_OPCODE_SYNTAX("{n}NOP  {e}[UNOFFICIAL]", "{n}.db {o}$0B", "{n}.db {o}$0B", GG_OPCode_Type_Implied),
    GG_OPCODE("{n}TSB {o}$%04X", GG_OPCode_Type_2b),
    GG_OPCODE("{n}ORA {o}$%04X", GG_OPCode_Type_2b),
    GG_OPCODE("{n}ASL {o}$%04X", GG_OPCode_Type_2b),
    GG_OPCODE_SYNTAX("{n}BBR {o}0,$%02X,$%04X  {e}[%+d]", "{n}BBR0 {o}<$%02X,$%04X", "{n}BBR0 {o}$%02X,$%02X", GG_OPCode_Type_1b_1b_Relative),

    GG_OPCODE_SYNTAX("{n}BPL {o}$%04X  {e}[%+d]", "{n}BPL {o}$%04X", "{n}BPL {o}$%02X", GG_OPCode_Type_1b_Relative),
    GG_OPCODE_SYNTAX("{n}ORA {o}($%02X),Y", "{n}ORA {o}[$%02X],Y", "{n}ORA {o}($%02X),Y", GG_OPCode_Type_1b),
    GG_OPCODE_SYNTAX("{n}ORA {o}($%02X)", "{n}ORA {o}[$%02X]", "{n}ORA {o}($%02X)", GG_OPCode_Type_1b),
    GG_OPCODE_SYNTAX("{n}ST1 {o}#$%02X  {e}[LSB]", "{n}ST1 {o}#$%02X", "{n}ST1 {o}#$%02X", GG_OPCode_Type_1b),
    GG_OPCODE_SYNTAX("{n}TRB {o}$%02X", "{n}TRB {o}<$%02X", "{n}TRB {o}$%02X", GG_OPCode_Type_1b),
    GG_OPCODE_SYNTAX("{n}ORA {o}$%02X,X", "{n}ORA {o}<$%02X,X", "{n}ORA {o}$%02X,X", GG_OPCode_Type_1b),
    GG_OPCODE_SYNTAX("{n}ASL {o}$%02X,X", "{n}ASL {o}<$%02X,X", "{n}ASL {o}$%02X,X", GG_OPCode_Type_1b),
    GG_OPCODE_SYNTAX("{n}RMB {o}1,$%02X", "{n}RMB1 {o}<$%02X", "{n}RMB1 {o}$%02X", GG_OPCode_Type_1b),
    GG_OPCODE("{n}CLC", GG_OPCode_Type_Implied),
    GG_OPCODE("{n}ORA {o}$%04X,Y", GG_OPCode_Type_2b),
    GG_OPCODE_SYNTAX("{n}INC {o}A", "{n}INC {o}A", "{n}INA", GG_OPCode_Type_Implied),
    GG_OPCODE_SYNTAX("{n}NOP  {e}[UNOFFICIAL]", "{n}.db {o}$1B", "{n}.db {o}$1B", GG_OPCode_Type_Implied),
    GG_OPCODE("{n}TRB {o}$%04X", GG_OPCode_Type_2b),
    GG_OPCODE("{n}ORA {o}$%04X,X", GG_OPCode_Type_2b),
    GG_OPCODE("{n}ASL {o}$%04X,X", GG_OPCode_Type_2b),
    GG_OPCODE_SYNTAX("{n}BBR {o}1,$%02X,$%04X  {e}[%+d]", "{n}BBR1 {o}<$%02X,$%04X", "{n}BBR1 {o}$%02X,$%02X", GG_OPCode_Type_1b_1b_Relative),

    GG_OPCODE("{n}JSR {o}$%04X", GG_OPCode_Type_2b),
    GG_OPCODE_SYNTAX("{n}AND {o}$(%02X,X)", "{n}AND {o}[$%02X,X]", "{n}AND {o}($%02X,X)", GG_OPCode_Type_1b),
    GG_OPCODE("{n}SAX", GG_OPCode_Type_Implied),
    GG_OPCODE_SYNTAX("{n}ST2 {o}#$%02X  {e}[MSB]", "{n}ST2 {o}#$%02X", "{n}ST2 {o}#$%02X", GG_OPCode_Type_1b),
    GG_OPCODE_SYNTAX("{n}BIT {o}$%02X", "{n}BIT {o}<$%02X", "{n}BIT {o}$%02X", GG_OPCode_Type_1b),
    GG_OPCODE_SYNTAX("{n}AND {o}$%02X", "{n}AND {o}<$%02X", "{n}AND {o}$%02X", GG_OPCode_Type_1b),
    GG_OPCODE_SYNTAX("{n}ROL {o}$%02X", "{n}ROL {o}<$%02X", "{n}ROL {o}$%02X", GG_OPCode_Type_1b),
    GG_OPCODE_SYNTAX("{n}RMB {o}2,$%02X", "{n}RMB2 {o}<$%02X", "{n}RMB2 {o}$%02X", GG_OPCode_Type_1b),
    GG_OPCODE("{n}PLP", GG_OPCode_Type_Implied),
    GG_OPCODE("{n}AND {o}#$%02X", GG_OPCode_Type_1b),
    GG_OPCODE("{n}ROL {o}A", GG_OPCode_Type_Implied),
    GG_OPCODE_SYNTAX("{n}NOP  {e}[UNOFFICIAL]", "{n}.db {o}$2B", "{n}.db {o}$2B", GG_OPCode_Type_Implied),
    GG_OPCODE("{n}BIT {o}$%04X", GG_OPCode_Type_2b),
    GG_OPCODE("{n}AND {o}$%04X", GG_OPCode_Type_2b),
    GG_OPCODE("{n}ROL {o}$%04X", GG_OPCode_Type_2b),
    GG_OPCODE_SYNTAX("{n}BBR {o}2,$%02X,$%04X  {e}[%+d]", "{n}BBR2 {o}<$%02X,$%04X", "{n}BBR2 {o}$%02X,$%02X", GG_OPCode_Type_1b_1b_Relative),

    GG_OPCODE_SYNTAX("{n}BMI {o}$%04X  {e}[%+d]", "{n}BMI {o}$%04X", "{n}BMI {o}$%02X", GG_OPCode_Type_1b_Relative),
    GG_OPCODE_SYNTAX("{n}AND {o}($%02X),Y", "{n}AND {o}[$%02X],Y", "{n}AND {o}($%02X),Y", GG_OPCode_Type_1b),
    GG_OPCODE_SYNTAX("{n}AND {o}($%02X)", "{n}AND {o}[$%02X]", "{n}AND {o}($%02X)", GG_OPCode_Type_1b),
    GG_OPCODE_SYNTAX("{n}NOP  {e}[UNOFFICIAL]", "{n}.db {o}$33", "{n}.db {o}$33", GG_OPCode_Type_Implied),
    GG_OPCODE_SYNTAX("{n}BIT {o}$%02X,X", "{n}BIT {o}<$%02X,X", "{n}BIT {o}$%02X,X", GG_OPCode_Type_1b),
    GG_OPCODE_SYNTAX("{n}AND {o}$%02X,X", "{n}AND {o}<$%02X,X", "{n}AND {o}$%02X,X", GG_OPCode_Type_1b),
    GG_OPCODE_SYNTAX("{n}ROL {o}$%02X,X", "{n}ROL {o}<$%02X,X", "{n}ROL {o}$%02X,X", GG_OPCode_Type_1b),
    GG_OPCODE_SYNTAX("{n}RMB {o}3,$%02X", "{n}RMB3 {o}<$%02X", "{n}RMB3 {o}$%02X", GG_OPCode_Type_1b),
    GG_OPCODE("{n}SEC", GG_OPCode_Type_Implied),
    GG_OPCODE("{n}AND {o}$%04X,Y", GG_OPCode_Type_2b),
    GG_OPCODE_SYNTAX("{n}DEC {o}A", "{n}DEC {o}A", "{n}DEA", GG_OPCode_Type_Implied),
    GG_OPCODE_SYNTAX("{n}NOP  {e}[UNOFFICIAL]", "{n}.db {o}$3B", "{n}.db {o}$3B", GG_OPCode_Type_Implied),
    GG_OPCODE("{n}BIT {o}$%04X,X", GG_OPCode_Type_2b),
    GG_OPCODE("{n}AND {o}$%04X,X", GG_OPCode_Type_2b),
    GG_OPCODE("{n}ROL {o}$%04X,X", GG_OPCode_Type_2b),
    GG_OPCODE_SYNTAX("{n}BBR {o}3,$%02X,$%04X  {e}[%+d]", "{n}BBR3 {o}<$%02X,$%04X", "{n}BBR3 {o}$%02X,$%02X", GG_OPCode_Type_1b_1b_Relative),

    GG_OPCODE("{n}RTI", GG_OPCode_Type_Implied),
    GG_OPCODE_SYNTAX("{n}EOR {o}$(%02X,X)", "{n}EOR {o}[$%02X,X]", "{n}EOR {o}($%02X,X)", GG_OPCode_Type_1b),
    GG_OPCODE("{n}SAY", GG_OPCode_Type_Implied),
    GG_OPCODE_SYNTAX("{n}TMA {o}#$%02X", "{n}TMA {o}#%d", "{n}TMA {o}#$%02X", GG_OPCode_Type_MPR),
    GG_OPCODE_SYNTAX("{n}BSR {o}$%04X  {e}[%+d]", "{n}BSR {o}$%04X", "{n}BSR {o}$%02X", GG_OPCode_Type_1b_Relative),
    GG_OPCODE_SYNTAX("{n}EOR {o}$%02X", "{n}EOR {o}<$%02X", "{n}EOR {o}$%02X", GG_OPCode_Type_1b),
    GG_OPCODE_SYNTAX("{n}LSR {o}$%02X", "{n}LSR {o}<$%02X", "{n}LSR {o}$%02X", GG_OPCode_Type_1b),
    GG_OPCODE_SYNTAX("{n}RMB {o}4,$%02X", "{n}RMB4 {o}<$%02X", "{n}RMB4 {o}$%02X", GG_OPCode_Type_1b),
    GG_OPCODE("{n}PHA", GG_OPCode_Type_Implied),
    GG_OPCODE("{n}EOR {o}#$%02X", GG_OPCode_Type_1b),
    GG_OPCODE("{n}LSR {o}A", GG_OPCode_Type_Implied),
    GG_OPCODE_SYNTAX("{n}NOP  {e}[UNOFFICIAL]", "{n}.db {o}$4B", "{n}.db {o}$4B", GG_OPCode_Type_Implied),
    GG_OPCODE("{n}JMP {o}$%04X", GG_OPCode_Type_2b),
    GG_OPCODE("{n}EOR {o}$%04X", GG_OPCode_Type_2b),
    GG_OPCODE("{n}LSR {o}$%04X", GG_OPCode_Type_2b),
    GG_OPCODE_SYNTAX("{n}BBR {o}4,$%02X,$%04X  {e}[%+d]", "{n}BBR4 {o}<$%02X,$%04X", "{n}BBR4 {o}$%02X,$%02X", GG_OPCode_Type_1b_1b_Relative),

    GG_OPCODE_SYNTAX("{n}BVC {o}$%04X  {e}[%+d]", "{n}BVC {o}$%04X", "{n}BVC {o}$%02X", GG_OPCode_Type_1b_Relative),
    GG_OPCODE_SYNTAX("{n}EOR {o}($%02X),Y", "{n}EOR {o}[$%02X],Y", "{n}EOR {o}($%02X),Y", GG_OPCode_Type_1b),
    GG_OPCODE_SYNTAX("{n}EOR {o}($%02X)", "{n}EOR {o}[$%02X]", "{n}EOR {o}($%02X)", GG_OPCode_Type_1b),
    GG_OPCODE_SYNTAX("{n}TAM {o}#$%02X", "{n}TAM {o}#%d", "{n}TAM {o}#$%02X", GG_OPCode_Type_MPR),
    GG_OPCODE("{n}CSL", GG_OPCode_Type_Implied),
    GG_OPCODE_SYNTAX("{n}EOR {o}$%02X,X", "{n}EOR {o}<$%02X,X", "{n}EOR {o}$%02X,X", GG_OPCode_Type_1b),
    GG_OPCODE_SYNTAX("{n}LSR {o}$%02X,X", "{n}LSR {o}<$%02X,X", "{n}LSR {o}$%02X,X", GG_OPCode_Type_1b),
    GG_OPCODE_SYNTAX("{n}RMB {o}5,$%02X", "{n}RMB5 {o}<$%02X", "{n}RMB5 {o}$%02X", GG_OPCode_Type_1b),
    GG_OPCODE("{n}CLI", GG_OPCode_Type_Implied),
    GG_OPCODE("{n}EOR {o}$%04X,Y", GG_OPCode_Type_2b),
    GG_OPCODE("{n}PHY", GG_OPCode_Type_Implied),
    GG_OPCODE_SYNTAX("{n}NOP  {e}[UNOFFICIAL]", "{n}.db {o}$5B", "{n}.db {o}$5B", GG_OPCode_Type_Implied),
    GG_OPCODE_SYNTAX("{n}NOP  {e}[UNOFFICIAL]", "{n}.db {o}$5C", "{n}.db {o}$5C", GG_OPCode_Type_Implied),
    GG_OPCODE("{n}EOR {o}$%04X,X", GG_OPCode_Type_2b),
    GG_OPCODE("{n}LSR {o}$%04X,X", GG_OPCode_Type_2b),
    GG_OPCODE_SYNTAX("{n}BBR {o}5,$%02X,$%04X  {e}[%+d]", "{n}BBR5 {o}<$%02X,$%04X", "{n}BBR5 {o}$%02X,$%02X", GG_OPCode_Type_1b_1b_Relative),

    GG_OPCODE("{n}RTS", GG_OPCode_Type_Implied),
    GG_OPCODE_SYNTAX("{n}ADC {o}$(%02X,X)", "{n}ADC {o}[$%02X,X]", "{n}ADC {o}($%02X,X)", GG_OPCode_Type_1b),
    GG_OPCODE("{n}CLA", GG_OPCode_Type_Implied),
    GG_OPCODE_SYNTAX("{n}NOP  {e}[UNOFFICIAL]", "{n}.db {o}$63", "{n}.db {o}$63", GG_OPCode_Type_Implied),
    GG_OPCODE_SYNTAX("{n}STZ {o}$%02X", "{n}STZ {o}<$%02X", "{n}STZ {o}$%02X", GG_OPCode_Type_1b),
    GG_OPCODE_SYNTAX("{n}ADC {o}$%02X", "{n}ADC {o}<$%02X", "{n}ADC {o}$%02X", GG_OPCode_Type_1b),
    GG_OPCODE_SYNTAX("{n}ROR {o}$%02X", "{n}ROR {o}<$%02X", "{n}ROR {o}$%02X", GG_OPCode_Type_1b),
    GG_OPCODE_SYNTAX("{n}RMB {o}6,$%02X", "{n}RMB6 {o}<$%02X", "{n}RMB6 {o}$%02X", GG_OPCode_Type_1b),
    GG_OPCODE("{n}PLA", GG_OPCode_Type_Implied),
    GG_OPCODE("{n}ADC {o}#$%02X", GG_OPCode_Type_1b),
    GG_OPCODE("{n}ROR {o}A", GG_OPCode_Type_Implied),
    GG_OPCODE_SYNTAX("{n}NOP  {e}[UNOFFICIAL]", "{n}.db {o}$6B", "{n}.db {o}$6B", GG_OPCode_Type_Implied),
    GG_OPCODE_SYNTAX("{n}JMP {o}($%04X)", "{n}JMP {o}[$%04X]", "{n}JMP {o}($%04X)", GG_OPCode_Type_2b),
    GG_OPCODE("{n}ADC {o}$%04X", GG_OPCode_Type_2b),
    GG_OPCODE("{n}ROR {o}$%04X", GG_OPCode_Type_2b),
    GG_OPCODE_SYNTAX("{n}BBR {o}6,$%02X,$%04X  {e}[%+d]", "{n}BBR6 {o}<$%02X,$%04X", "{n}BBR6 {o}$%02X,$%02X", GG_OPCode_Type_1b_1b_Relative),

    GG_OPCODE_SYNTAX("{n}BVS {o}$%04X  {e}[%+d]", "{n}BVS {o}$%04X", "{n}BVS {o}$%02X", GG_OPCode_Type_1b_Relative),
    GG_OPCODE_SYNTAX("{n}ADC {o}($%02X),Y", "{n}ADC {o}[$%02X],Y", "{n}ADC {o}($%02X),Y", GG_OPCode_Type_1b),
    GG_OPCODE_SYNTAX("{n}ADC {o}($%02X)", "{n}ADC {o}[$%02X]", "{n}ADC {o}($%02X)", GG_OPCode_Type_1b),
    GG_OPCODE_SYNTAX("{n}TII {o}$%04X,$%04X,#$%04X", "{n}TII {o}$%04X,$%04X,$%04X", "{n}TII {o}$%04X,$%04X,$%04X", GG_OPCode_Type_2b_2b_2b),
    GG_OPCODE_SYNTAX("{n}STZ {o}$%02X,X", "{n}STZ {o}<$%02X,X", "{n}STZ {o}$%02X,X", GG_OPCode_Type_1b),
    GG_OPCODE_SYNTAX("{n}ADC {o}$%02X,X", "{n}ADC {o}<$%02X,X", "{n}ADC {o}$%02X,X", GG_OPCode_Type_1b),
    GG_OPCODE_SYNTAX("{n}ROR {o}$%02X,X", "{n}ROR {o}<$%02X,X", "{n}ROR {o}$%02X,X", GG_OPCode_Type_1b),
    GG_OPCODE_SYNTAX("{n}RMB {o}7,$%02X", "{n}RMB7 {o}<$%02X", "{n}RMB7 {o}$%02X", GG_OPCode_Type_1b),
    GG_OPCODE("{n}SEI", GG_OPCode_Type_Implied),
    GG_OPCODE("{n}ADC {o}$%04X,Y", GG_OPCode_Type_2b),
    GG_OPCODE("{n}PLY", GG_OPCode_Type_Implied),
    GG_OPCODE_SYNTAX("{n}NOP  {e}[UNOFFICIAL]", "{n}.db {o}$7B", "{n}.db {o}$7B", GG_OPCode_Type_Implied),
    GG_OPCODE_SYNTAX("{n}JMP {o}$(%04X,X)", "{n}JMP {o}[$%04X,X]", "{n}JMP {o}($%04X,X)", GG_OPCode_Type_2b),
    GG_OPCODE("{n}ADC {o}$%04X,X", GG_OPCode_Type_2b),
    GG_OPCODE("{n}ROR {o}$%04X,X", GG_OPCode_Type_2b),
    GG_OPCODE_SYNTAX("{n}BBR {o}7,$%02X,$%04X  {e}[%+d]", "{n}BBR7 {o}<$%02X,$%04X", "{n}BBR7 {o}$%02X,$%02X", GG_OPCode_Type_1b_1b_Relative),

    GG_OPCODE_SYNTAX("{n}BRA {o}$%04X  {e}[%+d]", "{n}BRA {o}$%04X", "{n}BRA {o}$%02X", GG_OPCode_Type_1b_Relative),
    GG_OPCODE_SYNTAX("{n}STA {o}$(%02X,X)", "{n}STA {o}[$%02X,X]", "{n}STA {o}($%02X,X)", GG_OPCode_Type_1b),
    GG_OPCODE("{n}CLX", GG_OPCode_Type_Implied),
    GG_OPCODE_SYNTAX("{n}TST {o}#$%02X,$%02X", "{n}TST {o}#$%02X,<$%02X", "{n}TST {o}#$%02X,$%02X", GG_OPCode_Type_1b_1b),
    GG_OPCODE_SYNTAX("{n}STY {o}$%02X", "{n}STY {o}<$%02X", "{n}STY {o}$%02X", GG_OPCode_Type_1b),
    GG_OPCODE_SYNTAX("{n}STA {o}$%02X", "{n}STA {o}<$%02X", "{n}STA {o}$%02X", GG_OPCode_Type_1b),
    GG_OPCODE_SYNTAX("{n}STX {o}$%02X", "{n}STX {o}<$%02X", "{n}STX {o}$%02X", GG_OPCode_Type_1b),
    GG_OPCODE_SYNTAX("{n}SMB {o}0,$%02X", "{n}SMB0 {o}<$%02X", "{n}SMB0 {o}$%02X", GG_OPCode_Type_1b),
    GG_OPCODE("{n}DEY", GG_OPCode_Type_Implied),
    GG_OPCODE("{n}BIT {o}#$%02X", GG_OPCode_Type_1b),
    GG_OPCODE("{n}TXA", GG_OPCode_Type_Implied),
    GG_OPCODE_SYNTAX("{n}NOP  {e}[UNOFFICIAL]", "{n}.db {o}$8B", "{n}.db {o}$8B", GG_OPCode_Type_Implied),
    GG_OPCODE("{n}STY {o}$%04X", GG_OPCode_Type_2b),
    GG_OPCODE("{n}STA {o}$%04X", GG_OPCode_Type_2b),
    GG_OPCODE("{n}STX {o}$%04X", GG_OPCode_Type_2b),
    GG_OPCODE_SYNTAX("{n}BBS {o}0,$%02X,$%04X  {e}[%+d]", "{n}BBS0 {o}<$%02X,$%04X", "{n}BBS0 {o}$%02X,$%02X", GG_OPCode_Type_1b_1b_Relative),

    GG_OPCODE_SYNTAX("{n}BCC {o}$%04X  {e}[%+d]", "{n}BCC {o}$%04X", "{n}BCC {o}$%02X", GG_OPCode_Type_1b_Relative),
    GG_OPCODE_SYNTAX("{n}STA {o}($%02X),Y", "{n}STA {o}[$%02X],Y", "{n}STA {o}($%02X),Y", GG_OPCode_Type_1b),
    GG_OPCODE_SYNTAX("{n}STA {o}($%02X)", "{n}STA {o}[$%02X]", "{n}STA {o}($%02X)", GG_OPCode_Type_1b),
    GG_OPCODE("{n}TST {o}#$%02X,$%04X", GG_OPCode_Type_1b_2b),
    GG_OPCODE_SYNTAX("{n}STY {o}$%02X,X", "{n}STY {o}<$%02X,X", "{n}STY {o}$%02X,X", GG_OPCode_Type_1b),
    GG_OPCODE_SYNTAX("{n}STA {o}$%02X,X", "{n}STA {o}<$%02X,X", "{n}STA {o}$%02X,X", GG_OPCode_Type_1b),
    GG_OPCODE_SYNTAX("{n}STX {o}$%02X,Y", "{n}STX {o}<$%02X,Y", "{n}STX {o}$%02X,Y", GG_OPCode_Type_1b),
    GG_OPCODE_SYNTAX("{n}SMB {o}1,$%02X", "{n}SMB1 {o}<$%02X", "{n}SMB1 {o}$%02X", GG_OPCode_Type_1b),
    GG_OPCODE("{n}TYA", GG_OPCode_Type_Implied),
    GG_OPCODE("{n}STA {o}$%04X,Y", GG_OPCode_Type_2b),
    GG_OPCODE("{n}TXS", GG_OPCode_Type_Implied),
    GG_OPCODE_SYNTAX("{n}NOP  {e}[UNOFFICIAL]", "{n}.db {o}$9B", "{n}.db {o}$9B", GG_OPCode_Type_Implied),
    GG_OPCODE("{n}STZ {o}$%04X", GG_OPCode_Type_2b),
    GG_OPCODE("{n}STA {o}$%04X,X", GG_OPCode_Type_2b),
    GG_OPCODE("{n}STZ {o}$%04X,X", GG_OPCode_Type_2b),
    GG_OPCODE_SYNTAX("{n}BBS {o}1,$%02X,$%04X  {e}[%+d]", "{n}BBS1 {o}<$%02X,$%04X", "{n}BBS1 {o}$%02X,$%02X", GG_OPCode_Type_1b_1b_Relative),

    GG_OPCODE("{n}LDY {o}#$%02X", GG_OPCode_Type_1b),
    GG_OPCODE_SYNTAX("{n}LDA {o}$(%02X,X)", "{n}LDA {o}[$%02X,X]", "{n}LDA {o}($%02X,X)", GG_OPCode_Type_1b),
    GG_OPCODE("{n}LDX {o}#$%02X", GG_OPCode_Type_1b),
    GG_OPCODE_SYNTAX("{n}TST {o}#$%02X,$%02X,X", "{n}TST {o}#$%02X,<$%02X,X", "{n}TST {o}#$%02X,$%02X,X", GG_OPCode_Type_1b_1b),
    GG_OPCODE_SYNTAX("{n}LDY {o}$%02X", "{n}LDY {o}<$%02X", "{n}LDY {o}$%02X", GG_OPCode_Type_1b),
    GG_OPCODE_SYNTAX("{n}LDA {o}$%02X", "{n}LDA {o}<$%02X", "{n}LDA {o}$%02X", GG_OPCode_Type_1b),
    GG_OPCODE_SYNTAX("{n}LDX {o}$%02X", "{n}LDX {o}<$%02X", "{n}LDX {o}$%02X", GG_OPCode_Type_1b),
    GG_OPCODE_SYNTAX("{n}SMB {o}2,$%02X", "{n}SMB2 {o}<$%02X", "{n}SMB2 {o}$%02X", GG_OPCode_Type_1b),
    GG_OPCODE("{n}TAY", GG_OPCode_Type_Implied),
    GG_OPCODE("{n}LDA {o}#$%02X", GG_OPCode_Type_1b),
    GG_OPCODE("{n}TAX", GG_OPCode_Type_Implied),
    GG_OPCODE_SYNTAX("{n}NOP  {e}[UNOFFICIAL]", "{n}.db {o}$AB", "{n}.db {o}$AB", GG_OPCode_Type_Implied),
    GG_OPCODE("{n}LDY {o}$%04X", GG_OPCode_Type_2b),
    GG_OPCODE("{n}LDA {o}$%04X", GG_OPCode_Type_2b),
    GG_OPCODE("{n}LDX {o}$%04X", GG_OPCode_Type_2b),
    GG_OPCODE_SYNTAX("{n}BBS {o}2,$%02X,$%04X  {e}[%+d]", "{n}BBS2 {o}<$%02X,$%04X", "{n}BBS2 {o}$%02X,$%02X", GG_OPCode_Type_1b_1b_Relative),

    GG_OPCODE_SYNTAX("{n}BCS {o}$%04X  {e}[%+d]", "{n}BCS {o}$%04X", "{n}BCS {o}$%02X", GG_OPCode_Type_1b_Relative),
    GG_OPCODE_SYNTAX("{n}LDA {o}($%02X),Y", "{n}LDA {o}[$%02X],Y", "{n}LDA {o}($%02X),Y", GG_OPCode_Type_1b),
    GG_OPCODE_SYNTAX("{n}LDA {o}($%02X)", "{n}LDA {o}[$%02X]", "{n}LDA {o}($%02X)", GG_OPCode_Type_1b),
    GG_OPCODE("{n}TST {o}#$%02X,$%04X,X", GG_OPCode_Type_1b_2b),
    GG_OPCODE_SYNTAX("{n}LDY {o}$%02X,X", "{n}LDY {o}<$%02X,X", "{n}LDY {o}$%02X,X", GG_OPCode_Type_1b),
    GG_OPCODE_SYNTAX("{n}LDA {o}$%02X,X", "{n}LDA {o}<$%02X,X", "{n}LDA {o}$%02X,X", GG_OPCode_Type_1b),
    GG_OPCODE_SYNTAX("{n}LDX {o}$%02X,Y", "{n}LDX {o}<$%02X,Y", "{n}LDX {o}$%02X,Y", GG_OPCode_Type_1b),
    GG_OPCODE_SYNTAX("{n}SMB {o}3,$%02X", "{n}SMB3 {o}<$%02X", "{n}SMB3 {o}$%02X", GG_OPCode_Type_1b),
    GG_OPCODE("{n}CLV", GG_OPCode_Type_Implied),
    GG_OPCODE("{n}LDA {o}$%04X,Y", GG_OPCode_Type_2b),
    GG_OPCODE("{n}TSX", GG_OPCode_Type_Implied),
    GG_OPCODE_SYNTAX("{n}NOP  {e}[UNOFFICIAL]", "{n}.db {o}$BB", "{n}.db {o}$BB", GG_OPCode_Type_Implied),
    GG_OPCODE("{n}LDY {o}$%04X,X", GG_OPCode_Type_2b),
    GG_OPCODE("{n}LDA {o}$%04X,X", GG_OPCode_Type_2b),
    GG_OPCODE("{n}LDX {o}$%04X,Y", GG_OPCode_Type_2b),
    GG_OPCODE_SYNTAX("{n}BBS {o}3,$%02X,$%04X  {e}[%+d]", "{n}BBS3 {o}<$%02X,$%04X", "{n}BBS3 {o}$%02X,$%02X", GG_OPCode_Type_1b_1b_Relative),

    GG_OPCODE("{n}CPY {o}#$%02X", GG_OPCode_Type_1b),
    GG_OPCODE_SYNTAX("{n}CMP {o}$(%02X,X)", "{n}CMP {o}[$%02X,X]", "{n}CMP {o}($%02X,X)", GG_OPCode_Type_1b),
    GG_OPCODE("{n}CLY", GG_OPCode_Type_Implied),
    GG_OPCODE_SYNTAX("{n}TDD {o}$%04X,$%04X,#$%04X", "{n}TDD {o}$%04X,$%04X,$%04X", "{n}TDD {o}$%04X,$%04X,$%04X", GG_OPCode_Type_2b_2b_2b),
    GG_OPCODE_SYNTAX("{n}CPY {o}$%02X", "{n}CPY {o}<$%02X", "{n}CPY {o}$%02X", GG_OPCode_Type_1b),
    GG_OPCODE_SYNTAX("{n}CMP {o}$%02X", "{n}CMP {o}<$%02X", "{n}CMP {o}$%02X", GG_OPCode_Type_1b),
    GG_OPCODE_SYNTAX("{n}DEC {o}$%02X", "{n}DEC {o}<$%02X", "{n}DEC {o}$%02X", GG_OPCode_Type_1b),
    GG_OPCODE_SYNTAX("{n}SMB {o}4,$%02X", "{n}SMB4 {o}<$%02X", "{n}SMB4 {o}$%02X", GG_OPCode_Type_1b),
    GG_OPCODE("{n}INY", GG_OPCode_Type_Implied),
    GG_OPCODE("{n}CMP {o}#$%02X", GG_OPCode_Type_1b),
    GG_OPCODE("{n}DEX", GG_OPCode_Type_Implied),
    GG_OPCODE_SYNTAX("{n}NOP  {e}[UNOFFICIAL]", "{n}.db {o}$CB", "{n}.db {o}$CB", GG_OPCode_Type_Implied),
    GG_OPCODE("{n}CPY {o}$%04X", GG_OPCode_Type_2b),
    GG_OPCODE("{n}CMP {o}$%04X", GG_OPCode_Type_2b),
    GG_OPCODE("{n}DEC {o}$%04X", GG_OPCode_Type_2b),
    GG_OPCODE_SYNTAX("{n}BBS {o}4,$%02X,$%04X  {e}[%+d]", "{n}BBS4 {o}<$%02X,$%04X", "{n}BBS4 {o}$%02X,$%02X", GG_OPCode_Type_1b_1b_Relative),

    GG_OPCODE_SYNTAX("{n}BNE {o}$%04X  {e}[%+d]", "{n}BNE {o}$%04X", "{n}BNE {o}$%02X", GG_OPCode_Type_1b_Relative),
    GG_OPCODE_SYNTAX("{n}CMP {o}($%02X),Y", "{n}CMP {o}[$%02X],Y", "{n}CMP {o}($%02X),Y", GG_OPCode_Type_1b),
    GG_OPCODE_SYNTAX("{n}CMP {o}($%02X)", "{n}CMP {o}[$%02X]", "{n}CMP {o}($%02X)", GG_OPCode_Type_1b),
    GG_OPCODE_SYNTAX("{n}TIN {o}$%04X,$%04X,#$%04X", "{n}TIN {o}$%04X,$%04X,$%04X", "{n}TIN {o}$%04X,$%04X,$%04X", GG_OPCode_Type_2b_2b_2b),
    GG_OPCODE("{n}CSH", GG_OPCode_Type_Implied),
    GG_OPCODE_SYNTAX("{n}CMP {o}$%02X,X", "{n}CMP {o}<$%02X,X", "{n}CMP {o}$%02X,X", GG_OPCode_Type_1b),
    GG_OPCODE_SYNTAX("{n}DEC {o}$%02X,X", "{n}DEC {o}<$%02X,X", "{n}DEC {o}$%02X,X", GG_OPCode_Type_1b),
    GG_OPCODE_SYNTAX("{n}SMB {o}5,$%02X", "{n}SMB5 {o}<$%02X", "{n}SMB5 {o}$%02X", GG_OPCode_Type_1b),
    GG_OPCODE("{n}CLD", GG_OPCode_Type_Implied),
    GG_OPCODE("{n}CMP {o}$%04X,Y", GG_OPCode_Type_2b),
    GG_OPCODE("{n}PHX", GG_OPCode_Type_Implied),
    GG_OPCODE_SYNTAX("{n}NOP  {e}[UNOFFICIAL]", "{n}.db {o}$DB", "{n}.db {o}$DB", GG_OPCode_Type_Implied),
    GG_OPCODE_SYNTAX("{n}NOP  {e}[UNOFFICIAL]", "{n}.db {o}$DC", "{n}.db {o}$DC", GG_OPCode_Type_Implied),
    GG_OPCODE("{n}CMP {o}$%04X,X", GG_OPCode_Type_2b),
    GG_OPCODE("{n}DEC {o}$%04X,X", GG_OPCode_Type_2b),
    GG_OPCODE_SYNTAX("{n}BBS {o}5,$%02X,$%04X  {e}[%+d]", "{n}BBS5 {o}<$%02X,$%04X", "{n}BBS5 {o}$%02X,$%02X", GG_OPCode_Type_1b_1b_Relative),

    GG_OPCODE("{n}CPX {o}#$%02X", GG_OPCode_Type_1b),
    GG_OPCODE_SYNTAX("{n}SBC {o}$(%02X,X)", "{n}SBC {o}[$%02X,X]", "{n}SBC {o}($%02X,X)", GG_OPCode_Type_1b),
    GG_OPCODE_SYNTAX("{n}NOP  {e}[UNOFFICIAL]", "{n}.db {o}$E2", "{n}.db {o}$E2", GG_OPCode_Type_Implied),
    GG_OPCODE_SYNTAX("{n}TIA {o}$%04X,$%04X,#$%04X", "{n}TIA {o}$%04X,$%04X,$%04X", "{n}TIA {o}$%04X,$%04X,$%04X", GG_OPCode_Type_2b_2b_2b),
    GG_OPCODE_SYNTAX("{n}CPX {o}$%02X", "{n}CPX {o}<$%02X", "{n}CPX {o}$%02X", GG_OPCode_Type_1b),
    GG_OPCODE_SYNTAX("{n}SBC {o}$%02X", "{n}SBC {o}<$%02X", "{n}SBC {o}$%02X", GG_OPCode_Type_1b),
    GG_OPCODE_SYNTAX("{n}INC {o}$%02X", "{n}INC {o}<$%02X", "{n}INC {o}$%02X", GG_OPCode_Type_1b),
    GG_OPCODE_SYNTAX("{n}SMB {o}6,$%02X", "{n}SMB6 {o}<$%02X", "{n}SMB6 {o}$%02X", GG_OPCode_Type_1b),
    GG_OPCODE("{n}INX", GG_OPCode_Type_Implied),
    GG_OPCODE("{n}SBC {o}#$%02X", GG_OPCode_Type_1b),
    GG_OPCODE("{n}NOP", GG_OPCode_Type_Implied),
    GG_OPCODE_SYNTAX("{n}NOP  {e}[UNOFFICIAL]", "{n}.db {o}$EB", "{n}.db {o}$EB", GG_OPCode_Type_Implied),
    GG_OPCODE("{n}CPX {o}$%04X", GG_OPCode_Type_2b),
    GG_OPCODE("{n}SBC {o}$%04X", GG_OPCode_Type_2b),
    GG_OPCODE("{n}INC {o}$%04X", GG_OPCode_Type_2b),
    GG_OPCODE_SYNTAX("{n}BBS {o}6,$%02X,$%04X  {e}[%+d]", "{n}BBS6 {o}<$%02X,$%04X", "{n}BBS6 {o}$%02X,$%02X", GG_OPCode_Type_1b_1b_Relative),

    GG_OPCODE_SYNTAX("{n}BEQ {o}$%04X  {e}[%+d]", "{n}BEQ {o}$%04X", "{n}BEQ {o}$%02X", GG_OPCode_Type_1b_Relative),
    GG_OPCODE_SYNTAX("{n}SBC {o}($%02X),Y", "{n}SBC {o}[$%02X],Y", "{n}SBC {o}($%02X),Y", GG_OPCode_Type_1b),
    GG_OPCODE_SYNTAX("{n}SBC {o}($%02X)", "{n}SBC {o}[$%02X]", "{n}SBC {o}($%02X)", GG_OPCode_Type_1b),
    GG_OPCODE_SYNTAX("{n}TAI {o}$%04X,$%04X,#$%04X", "{n}TAI {o}$%04X,$%04X,$%04X", "{n}TAI {o}$%04X,$%04X,$%04X", GG_OPCode_Type_2b_2b_2b),
    GG_OPCODE("{n}SET", GG_OPCode_Type_Implied),
    GG_OPCODE_SYNTAX("{n}SBC {o}$%02X,X", "{n}SBC {o}<$%02X,X", "{n}SBC {o}$%02X,X", GG_OPCode_Type_1b),
    GG_OPCODE_SYNTAX("{n}INC {o}$%02X,X", "{n}INC {o}<$%02X,X", "{n}INC {o}$%02X,X", GG_OPCode_Type_1b),
    GG_OPCODE_SYNTAX("{n}SMB {o}7,$%02X", "{n}SMB7 {o}<$%02X", "{n}SMB7 {o}$%02X", GG_OPCode_Type_1b),
    GG_OPCODE("{n}SED", GG_OPCode_Type_Implied),
    GG_OPCODE("{n}SBC {o}$%04X,Y", GG_OPCode_Type_2b),
    GG_OPCODE("{n}PLX", GG_OPCode_Type_Implied),
    GG_OPCODE_SYNTAX("{n}NOP  {e}[UNOFFICIAL]", "{n}.db {o}$FB", "{n}.db {o}$FB", GG_OPCode_Type_Implied),
    GG_OPCODE_SYNTAX("{n}NOP  {e}[UNOFFICIAL]", "{n}.db {o}$FC", "{n}.db {o}$FC", GG_OPCode_Type_Implied),
    GG_OPCODE("{n}SBC {o}$%04X,X", GG_OPCode_Type_2b),
    GG_OPCODE("{n}INC {o}$%04X,X", GG_OPCode_Type_2b),
    GG_OPCODE_SYNTAX("{n}BBS {o}7,$%02X,$%04X  {e}[%+d]", "{n}BBS7 {o}<$%02X,$%04X", "{n}BBS7 {o}$%02X,$%02X", GG_OPCode_Type_1b_1b_Relative)
};

#endif /* HUC6280_NAME_H */
